language: go
go:
  - master

install:
  - go get github.com/gohugoio/hugo

script:
  - hugo

deploy:
  local_dir: public
  repo: areller/areller.github.io
  target_branch: master
  provider: pages
  github_token: $GITHUB_TOKEN
  on:
    branch: master