os: linux

install:
  - mkdir hugo_build
  - wget https://github.com/gohugoio/hugo/releases/download/v0.41/hugo_0.41_Linux-64bit.tar.gz
  - tar -xvf hugo_0.41_Linux-64bit.tar.gz -C ./hugo_build
  - sudo mv ./hugo_build/hugo /usr/bin
  - rm -rf ./hugo_build
  - rm -rf hugo_0.41_Linux-64bit.tar.gz

script:
  - hugo

after_success: |
    git clone https://areller:$GITHUB_TOKEN@github.com/areller/areller.github.io
    cd areller.github.io
    git checkout --orphan master
    rm -rf .
    mv ../public/* ./
    git add -f --ignore-errors --all
    git -c user.name='travis' -c user.email='travis' commit -m init
    git push -f -q https://areller:$GITHUB_TOKEN@github.com/areller/areller.github.io master