os: linux

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.41/hugo_0.41_Linux-64bit.tar.gz
  - tar -xvf hugo_0.41_Linux-64bit.tar.gz
  - sudo mv hugo /usr/bin

script:
  - hugo

deploy:
  local_dir: public
  repo: areller/areller.github.io
  target_branch: master
  provider: pages
  github_token: $GITHUB_TOKEN
  on:
    branch: master